### ISSUE TITLE
create payment doesn't work

### ISSUE THREAD

**Issue by AkaKwak** [Team-stash/le_circographe#122]
When i try to pay with stripe. After filling the forme i have an error.
![image](https://github.com/user-attachments/assets/7c3ed1c6-c12b-4afd-9378-6ea5cfff4791)

**Comment by hellijah** [comment]
fix done and push on DEV branch

**Comment by hellijah** [comment]
it had to be done in 2 steps
payment add to be created first then event attendee could be recorded with payment.id
